config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get '/webhook', to: 'webhook#challenge'
  post '/webhook', to: 'webhook#post'
  resources :payment_notifications, only: [:create]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/:provider', to: 'sessions#unlink', via: [:delete]
  match '/', to: 'sites#load', constraints: { subdomain: /.+/}, via: [:get, :put, :patch, :delete]
  match '/*req', to: 'sites#load', constraints: { subdomain: /.+/}, via: [:get, :put, :patch, :delete]
  post '/verify', to: 'sites#passcode_verify'
  match '/', to: 'sites#send_contact', constraints: { subdomain: /.+/}, via: [:post]
  match '/*req', to: 'sites#send_contact', constraints: { subdomain: /.+/}, via: [:post]
  root 'sites#index'
  get '/logout', to: 'sessions#destroy'
  get '/auth/dropbox', to: 'sessions#new'
  get '/news/css/main.css', to: 'news#css'
  get '/news/:path', to: 'news#show'
  get '/news', to: 'news#index'
  resources :reviews

  get '/about', to: 'pages#about'
  get '/faq', to: 'pages#faq'
  get '/tos', to: 'pages#tos'
  get '/source', to: 'pages#source'
  get '/contact', to: 'pages#contact'
  post '/contact', to: 'pages#contact_create'
  get '/thanks', to: 'pages#thanks'
  get '/pricing', to: 'pages#pricing'
  get '/feedback', to: 'pages#feedback'
  post '/feedback', to: 'pages#feedback_create'
  get '/folders', to: 'sites#folders'
  get '/files', to: 'sites#files'
  get '/admin', to: 'pages#admin'
  get '/account', to: 'pages#account'

  post "/versions/:id/revert", to: "versions#revert", as: "revert_version"
  post "/checkout", to: "payments#checkout"
  resources :sites, path: '' do
    delete 'password'
  end
  namespace :api do
    get '/dropbox/files', to: 'dropbox#files'
    get '/dropbox/folders', to: 'dropbox#folders'
    get '/google/files', to: 'google#files'
    get '/google/folders', to: 'google#folders'
  end
end

app/models/site.rb
require 'resolv'

class Site < ActiveRecord::Base
  belongs_to :user
  attr_accessor :passcode
  has_many :clicks
  has_many :contacts
  has_paper_trail
  validates :subdomain, uniqueness: { case_sensititve: false }
  validates :name, presence: true
  validates :domain, uniqueness: { case_sensititve: false, allow_blank: true }
  validate :domain_isnt_updog
  validate :domain_is_a_subdomain
  before_validation :namify
  after_create :notify_drip

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if passcode.present?
      self.encrypted_passcode= Digest::SHA2.hexdigest(passcode)
    end
  end

  def clear_password
    self.passcode = nil
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def creator
    self.user
  end

  def identity
    Identity.find_by(user: self.user, provider: self.provider)
  end

  def content path, dir = nil
    Resource.new(self, path).contents
  end

  def inject?
    (!self.creator.is_pro && self.creator.id > 1547) || !Rails.env.production?
  end

  def domain_isnt_updog
    if self.domain =~ /updog\.co/
      errors.add(:domain, "can't contain updog.co")
    end
  end

  def domain_is_a_subdomain
    if self.domain && self.domain != "" && self.domain !~ /\w+\.[\w-]+\.\w+/
      errors.add(:domain, "must have a subdomain like www.")
    end
  end

  def base_path
    case
    when self.document_root.present?
      self.document_root
    when self.db_path.present?
      self.db_path
    else
      "/" + self.name
    end
  end

  def link
    if self.domain && self.domain != ""
      self.domain
    else
      self.subdomain
    end
  end
  def self.created_today
    where("created_at > ?", Time.now.beginning_of_day)
  end
  def self.popular
    joins(:clicks).
    group("sites.id").
    where("clicks.created_at > ?", Time.now.beginning_of_day).
    order("count(clicks.id) DESC").
    limit(10)
  end
  def clicks_today
    clicks.where('created_at > ?', Time.now.beginning_of_day)
  end

  def dir folders
    folders.select{|folder| folder.id == self.google_id }.first if self.provider == 'google'
  end

  def domain_cname
    Resolv::DNS.open do |dns|
      records = dns.getresources(self.domain, Resolv::DNS::Resource::IN::CNAME)
      value = records.empty? ? nil : records.select{|record|
        record.name.to_s == 'updog.co'
      }.first
      value.name.to_s unless value.nil?
    end
  end

  def domain_configuration
    return nil unless self.domain.present?
    case
    when domain_cname.nil?
      {text:"There is no CNAME entry for #{self.domain}", klass: 'red'}
    when domain_cname != 'updog.co'
      {text:"The CNAME entry for #{self.domain} does not point to updog.co", klass: 'red'}
    else
      {text:"You have configured your domain correctly.", klass: 'green'}
    end
  end

  def protocol
    if self.domain.present?
      'http://'
    else
      'https://'
    end
  end

  private
  def notify_drip
    Drip.event self.creator.email, 'created a site'
  end
   def  namify
    self.name.downcase!
    self.name = self.name.gsub(/[^\w+]/,'-')
    self.name = self.name.gsub(/-+$/,'')
    self.name = self.name.gsub(/^-+/,'')
    self.subdomain = self.name + '.updog.co'
  end

end

app/controllers/sites_controller.rb
require 'digest'

class SitesController < ApplicationController
  layout "layouts/application"
  protect_from_forgery except: [:load, :passcode_verify, :send_contact]
  before_filter :authenticate, only: [:load]

  def send_contact
    if request.env["REQUEST_PATH"].match(/\.php$/)
      return render nothing: true
    end
    @site = Site.where("domain = ? OR subdomain = ?", request.host, request.host).first
    begin
      unless request.env['HTTP_REFERER'].match(@site.domain) || request.env['HTTP_REFERER'].match(@site.subdomain)
	       return render nothing: true
      end
      return redirect_to :back unless @site.creator.is_pro
      if @site.contact_email.present?
        email = @site.contact_email
      else
        email = @site.creator.email
      end
      @input = params.except(:action, :controller, :redirect)
      ContactMailer.user_mailer(email, @site.link, @input).deliver_now!
      @site.contacts.create!(params: @input)
      if params[:redirect]
	       redirect_to params[:redirect]
      else
	       redirect_to :back
      end
    rescue
      render nothing: true
    end
  end

  def index
    @sites = current_user.sites if current_user
    @count = File.read(Rails.root.join("tmp/request-count.txt"))
  end
  def edit
    return redirect_to root_path unless current_user
    @site = current_user.sites.find(params[:id])
    @providers = current_user.identities.map(&:provider)
    @identity = current_user.identities.find_by(provider: 'dropbox')
    session[:back_to] = request.url
  end
  def new
    session[:back_to] = request.url
    return redirect_to root_path unless current_user
    @sites = current_user.sites
    @providers = current_user.identities.map(&:provider)
    unless current_user.is_pro? || @sites.length == 0
      redirect_to root_path
    end
    provider = (@providers.include? 'dropbox') ? 'dropbox' : 'google'
    @site = Site.new(provider:provider)
    @identity = current_user.identities.find_by(provider: provider)
  end

  def show
    begin
      @site = current_user.sites.find(params[:id])
    rescue
      return render :html => '<div class="wrapper">Not Found</div>'.html_safe, :layout => true, status: 404, content_type: 'text/html'
    end
    @identity = current_user.identities.find_by(provider: @site.provider)
    @sites = current_user && current_user.sites || []
  end
  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy
    redirect_to sites_path, :notice => "Deleted. #{undo_link}?"
  end

  def authenticate
    @site = Site.where("domain = ? OR subdomain = ?", request.host, request.host).first
    return nil unless @site
    if request.env["REQUEST_PATH"] == @site.passcode_logo_path && @site.passcode_logo_path.present?
      return true
    end
    if @site.username.present?
      authenticate_or_request_with_http_basic do |name, password|
        name == @site.username && Digest::SHA2.hexdigest(password) == @site.encrypted_passcode
      end
    elsif @site.encrypted_passcode != "" && @site.encrypted_passcode != session["passcode_for_#{@site.id}"]
      if session["passcode_for_#{@site.id}"]
        flash.now[:alert] = "Passcode incorrect"
      end
      return render 'enter_passcode', layout: false
    end
  end

  def load
    @site = Site.where("domain = ? OR subdomain = ?", request.host, request.host).first
    if !@site
     render :html => '<div class="wrapper">Not Found</div>'.html_safe, :layout => true
     return
    end
    if request.env["HTTP_REFERER"] && request.env["HTTP_REFERER"].match(/www.hdvn1.com/)
      respond_to do |format|
        format.all { render({layout: false}.merge(html: 'hot linking not allowed')) }
      end
      return
    end
    @site.clicks.create(data:{
      path: request.env["REQUEST_URI"],
      ip: request.env["REMOTE_ADDR"],
      referer: request.env["HTTP_REFERER"]
    })
    uri = request.env['REQUEST_URI'] || request.env['PATH_INFO']
    @resource = Resource.new(@site, uri)
    if @site.provider == 'dropbox'
      if (uri && uri.match(/(\.zip|\.epub)/)) || params[:dl] == '1'
        return redirect_to @resource.get_temporary_link
      end
    end
    begin
      @content = @site.content( uri )
      if @content[:status] == 301
        location = Rails.env.test? ? uri + 'g' : @content[:location]
        #TODO fix capybara redirect issue
        return redirect_to location
      end
    rescue => e
      Rails.logger.error e.message
      Rails.logger.error e.backtrace.join("\n")
      if @site.provider == 'dropbox'
        return redirect_to @resource.get_temporary_link
      end
      return raise e
    end
    if @content[:html] == 'show folders'
      @path = URI.decode(uri)
      @entries = dropbox_files(@site.base_path + uri,@site.identity.full_access_token || @site.identity.access_token)
      return render 'directory_index', layout: false
    end
    begin
      @content[:html] = @content[:html].gsub("</body>","#{injectee(@site)}</body>").html_safe if @site.inject? && @content[:status] == 200
    rescue ArgumentError => e # probably invalid byte sequence
      Rails.logger.info "Invalid byte sequence error, not injecting"
    end
    respond_to do |format|
      format.all { render({layout: false}.merge(@content)) }
    end
  end

  def injectee site
    render_to_string(
      template: "sites/injectee",
      layout: false,
      locals: {
        site: site
      },
      formats: [:html]
    )
  end

  def create
    @site = current_user.sites.create site_params
    @identity = current_user.identities.find_by(provider: @site.provider)
    @providers = current_user.identities.map(&:provider)
    if @site.save
      if params[:site][:db_path].present? # probably using some existing code
        return redirect_to @site
      end
      path = "/" + @site.name
      content = render_to_string(:template => "sites/welcome", :layout => false, locals: {
          site: @site
      })
      if params[:site][:provider] == "dropbox"
        Resource.create_dropbox_folder(path, @identity.access_token)
        Resource.create_dropbox_file(path + "/index.html", content, @identity.access_token)
      elsif params[:site][:provider] == "google"
        Resource.google_init @identity, @site, content
      end
      redirect_to @site
    else

      render :new
    end
  end

  def update
    @site = current_user.sites.find(params[:id])
    @providers = current_user.identities.map(&:provider)
    @identity = current_user.identities.find_by(provider:@site.provider)
    if @site.update site_params
      redirect_to @site
    else
      render :edit
    end
  end

  def passcode_verify
    @site = Site.where("domain = ? OR subdomain = ?", request.host, request.host).first
    passcode = params[:passcode]
    session["passcode_for_#{@site.id}"] = Digest::SHA2.hexdigest(passcode)
    redirect_to :back
  end

  def password # for deletin
    @site = current_user.sites.find(params[:site_id])
    @site.update(encrypted_passcode: nil, username: nil)
    redirect_to :back
  end

  private

  def site_params
    params.require(:site).permit(:passcode_text, :passcode_logo_path, :contact_email, :name, :domain, :document_root, :render_markdown, :db_path, :passcode, :username, :provider)
  end

  def undo_link
    view_context.link_to("undo", revert_version_path(@site.versions.last), :method => :post)
  end

end

app/views/sites/_create.html.erb
<% if @sites.length < 1 || current_user.is_pro %>
  <div class='cf'>
    <div class='left'>
      <a href='<%= new_site_path %>' class='site-new btn-create'><i class="fa fa-plus-circle"></i> Create New Site</a>
    </div>
  </div>
<% else %>
  <a href='/pricing' class='dropbox'>Upgrade to Pro to Create Additional Sites</a>
<% end %>

app/views/sites/_form.html.erb
<style>
  .fa-cog{
    animation: goround 2s linear infinite;
    transform-origin: 50% 50%;
    margin-left:.25em;
  }
  .folder .fa-arrow-right{
    position:absolute;
    right:.5em;
    top:50%;
    transform: translateY(-50%);
  }
  .folder{
    position: relative;
    border-bottom:1px solid #ccc;
    padding:.5em;
    cursor: pointer;
  }
  .folder:hover{
    background:rgba(0%,48.3%,91.1%, .1);
  }
  .folder.active{
    background:rgba(0%,48.3%,91.1%, .2);
  }
  .folder a{
    text-decoration:none;
  }
  #db-chooser{
    overflow:hidden;
  }
  #db-chooser .back{
    transition: all .2s ease;
  }
  #db-chooser .back.hidden{
    margin-top:-2.5em;
    border:none;
  }
  @keyframes goround{
    0% {
      transform: rotate(0deg)
    }
    50% {
      transform: rotate(180deg)
    }
    100% {
      transform: rotate(360deg)
    }
  }
</style>
<% if @site.errors.any? %>
  <ul>
  <% @site.errors.full_messages.each do |e| %>
    <li> <%= e %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @site do |f| %>
  <label>Where would you like to host your site?</label>
  <div class='branded-radio js-toggle-select-folder'>
    <% @providers.each do |provider| %>
      <input type="radio" value="<%= provider %>"
      <% if @site.provider == provider %>
       checked="checked"
       <% end %>
      name="site[provider]" id="site_provider_<%= provider %>">
      <label for="site_provider_<%= provider %>"><%= provider.titleize %></label>
    <% end %>
  </div>
  <% if current_user.is_pro %>
    <div class='js-select-folder' style="<%= 'display:none' if @site.provider != 'dropbox' %>">
    <%= render 'select_folder' if @identity %>
    <script>
    $(".js-toggle-select-folder input").on("change", function(){
      console.log(this.value)
      if(this.value == 'dropbox'){
        $(".js-select-folder").show()
      }else{
        $(".js-select-folder").hide()
      }
    })
    </script>
    </div>
  <% end %>
  <%= f.label :name %>
  <div class='suffix-domain'>
    <%= f.text_field :name %>
  </div>
  <br>
  <%= f.label :domain do %>
    Domain
    <% if @site.domain.present? %>
      <span class='domain-configuration-status <%= @site.domain_configuration[:klass] %>'
            data-text='<%= @site.domain_configuration[:text] %>'>
      </span>

    <% end %>
  <% end %>
  <div class='domain-configuration-reason' style='display:none;'></div>
  <script>
    $(".domain-configuration-status").on("click", function(){
      $(".domain-configuration-reason").toggle().html(
        $(this).data("text")
      )
    })
  </script>
  <%= f.text_field :domain %> (optional) <small data-toggle=".instructions">What is this?</small><br><br>
  <% if current_user.is_pro %>
    <%= f.label :document_root %>
    <%= f.text_field :document_root, placeholder: '_site/' %> (optional) <br><br>
    <%= f.label :render_markdown %>
    <% if @site.id %>
      <%= f.check_box :render_markdown %> (optional)
    <% else %>
      <%= f.check_box :render_markdown, checked: true %>
    <% end %>
    <br><br>
    <div class="password-protect">
      <h2><i class='fa fa-lock'></i> Password Protection</h2>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :passcode %>
    <% if @site.encrypted_passcode %>
      This site is currently protected with a passcode. <%= link_to "Remove passcode", site_password_path(@site), method: :delete %>.<br>
    <% end %>
    <%= f.password_field :passcode, placeholder: 'Enter new passcode' %>
    <%= f.label :passcode_logo_path %>
    <%= f.text_field :passcode_logo_path, placeholder: '/images/logo.png' %>
    <%= f.label :passcode_text %>
    <%= f.text_field :passcode_text, placeholder: 'This site is protected with a passcode!' %>
    </div>
    <%= f.label :contact_email %>
    <small>Use an alternate email to receive contact form submissions.</small>
    <%= f.email_field :contact_email, class: 'input', placeholder: 'jesse@updog.co' %>
    <br><br>
  <% end %>
  <%= f.submit 'Save', :class => 'btn-create' %>
  <div class='instructions'>
  <p>Using your own custom domain? To enable this feature:</p>
  <ol>
    <li>Log in to your DNS host.</li>
    <li>Create a new CNAME record that points to updog.co</li>
    <li>Save your changes and wait for the DNS to propagate.</li>
    <li>Need help? email <a href='mailto:jesse@updog.co'>jesse@updog.co</a></li>
  </ol>
  <p>Here’s what that process looks like on Digital Ocean:</p>
  <img src='https://dl.dropboxusercontent.com/s/4ksisxk7khatbi7/do.gif?dl=0'>
  </div>
  <br>
  <br>
<% end %>

app/views/sites/directory_index.html.erb
<link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
<link rel='stylesheet' type='text/css' href='/markdown.css'>
<h1>Index of <%= @path %></h1>
<ul>
  <li><a href='../'>
    <i class='fa fa-undo'></i>
    Parent Directory
  </a></li>
<% @entries.each do |entry| %>
  <li class='<%= entry[".tag"] %>'>
  <i class='fa fa-<%= entry[".tag"] %>'></i>
    <% path = @path + '/'+  entry["name"] %>
    <% path = path.gsub('//','/') %>
    <%= link_to entry["name"], path %>
  </li>
<% end %>
</ul>

app/views/sites/edit.html.erb
<div class='wrapper'>
  <h2><%= @site.name %> settings</h2>
  <%= render 'form' %>
  <br>
  <hr>
  <br>
  <br>
  <a data-method="delete" rel="nofollow" href='<%= site_path(@site) %>' class='btn-delete'><i class="fa fa-times"></i>
  Delete <%= @site.name %></a>
</div>

app/views/sites/enter_passcode.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>UpDog</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <style media="screen">
      body, html{
        height:100%;
        margin:0;
      }
      body{
        font-family: 'Open Sans', sans-serif;
        display:flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
      }
      h2, form{
        width:100%;
        text-align:center;
      }
      img{
        max-width:80px;
      }
      input, button{
        font:inherit;
        background:#fff;
        border: 2px solid #000;
        padding:.5em 1em;
      }
      button{
        cursor:pointer;
      }
    </style>
  </head>
  <body>
    <form action="/verify" method="post">
      <a href="https://updog.co/">
        <% if @site.passcode_logo_path.present? %>
          <img src='<%= @site.passcode_logo_path %>'>
        <% else %>
         <img src="https://updog.co/logo.png">
        <% end %>
      </a>
      <h2>
        <% if @site.passcode_text.present? %>
          <%= @site.passcode_text %>
        <% else %>
          This site is protected with a passcode.
        <% end %>
      </h2>
      <%= flash[:alert] %>
      <input type="password" name="passcode" value="" placeholder="enter passcode">
      <button type="submit" name="button">Submit</button>
    </form>
  </body>
</html>

app/views/sites/index.html.erb
<% if current_user %>
  <div class='wrapper'>
    <div class='sites'>
      <%= render 'create' %>
      <% if @sites.length != 0 %>
        <h2>Your Sites:</h2>
        <ul>
        <% @sites.each do |s| %>
          <li class='cf'>
            <div class='left'><%= link_to s.name, site_path( s ) %> </div> <div class='right'> <%= link_to 'Settings', edit_site_path( s ), :class => 'btn-edit' %>
            </div>
          </li>
        <% end %>
        </ul>
      <% end %>
      <% if @sites.count == 0 %>
      <br>
      <p>
        Learn more about creating a site by viewing the video below:
      </p>
      <br>
      <iframe src="https://player.vimeo.com/video/194891291?byline=0&portrait=0" width="640" height="359" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      <p><a href="https://vimeo.com/194891291">Creating Your First UpDog Site</a> from <a href="https://vimeo.com/user34026330">Jesse Shawl</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
      <% end %>
    </div>
  </div>

  <% else %>

  <div class='wrapper index'>

    <h2>Real.</h2>
    <h2>Simple.</h2>
    <h2>Hosting.</h2>
    <p>Publish your own website for free using Dropbox or Google Drive</p>
      <a href='/auth/dropbox' class='dropbox js-track-link-click'><span class='fa fa-dropbox'></span> Log In with Dropbox</a>
      <a href='/auth/google' class='google js-track-link-click'><span class='fa fa-google'></span> Log In with Google</a>
    <br>
    <br>
    <h3><i class='fa fa-line-chart'></i>
       <span class='js-request-count'><%= number_with_delimiter(@count, :delimiter => ',') %></span>
      requests served, and counting!
    </h3>
    <p>Unlimited file transfer and <em>no</em> storage limits.</p>
    <h3><i class='fa fa-refresh'></i> Instantly Sync Your Website</h3>
    <p>Add HTML, CSS, and JS files to your dropbox folder. We'll connect those to a free domain name.</p>
    <h3><i class='fa fa-cloud-download'></i> No Software Required</h3>
    <p>Drag and drop files into your Dropbox folder to upload them instantly.</p>
    <h3><i class='fa fa-usd'></i> Straight-forward, Simple Pricing</h3>
    <p>Basic accounts are free, <em>forever</em>. Upgrade to a pro membership for a yearly fee.</p>
  </div>
  <script>
    $count = $(".js-request-count")
    var num = parseInt($count.html().replace(/,/g,''))
    var from = num - 180
    increment()
    function increment(){
      var delay = Math.floor(Math.random() * 800)
      setTimeout(function(){
        $count.html(commafy(from++))
        increment()
      }, delay)
    }
    function commafy(int){
      var str = "" + int
      var out = ""
      var digits = str.split("").reverse()
      for(var i = 0; i < digits.length; i++){
        if(i%3===0 && i !== 0){
          out += ","
        }
        out += digits[i]
      }
      return out.split("").reverse().join("")
    }
  </script>
  <% end %>

app/views/sites/load.css.erb
<%= @content %>

app/views/sites/load.html.erb
<%= @content %>

app/views/sites/new.html.erb
<div class='wrapper'>
  <h2>Create New Site</h2>
  <%= render 'form' %>
</div>

app/views/sites/show.html.erb
<div class='wrapper'>
  <div class='cf'>
  <div class='left'>
    <%= render 'create' %>
  </div>
  <div class='right'>
    <a href='<%= edit_site_path( @site ) %>' class='btn-edit'><i class="fa fa-gears"></i> Settings</a>

</div>
</div>

<h2 class='site-title'><a href='http://<%= @site.link %>'><%= @site.name %> <small><i class="fa fa-external-link"></i> </small></a></h2>
  <small>Created at <time><%= @site.created_at.strftime("%B %d, %Y") %></time></small>
<br>

<h3>Instructions</h3>
<ol>
  <li>Add your site to your Dropbox folder in <strong>
  <% if @site.provider == 'dropbox' %>
    <% if @site.db_path && @site.db_path != "" %>
      ~/Dropbox<%= @site.db_path %>
    <% else %>
      ~/Dropbox/Apps/updog/<%= @site.name %>/
    <% end %>
  <% end %>
  <% if @site.provider == 'google' %>
    ~/Google Drive/UpDog/<%= @site.name %>/
  <% end %>
  </strong></li>
  <li><a href='http://<%= @site.link %>'> View Site </a></li>
</ol>

<% if current_user.is_pro %>
<h3>Need a link?</h3>
<div id='file-explorer'>
  <% if @site.db_path.present? %>
    <file-explorer strip-string='<%= @site.db_path %>'></file-explorer>
  <% else %>
    <file-explorer strip-string='/<%= @site.name %>/'></file-explorer>
  <% end %>
</div>

<script type="text/x-template" id="folder-template">
  <div>
    <div v-if='canShowLink(file)'>
      <a :href="link(file, '<%= @site.link %>', '<%= @site.db_path %>', '<%= @site.name %>')" >
        <i :class="fileClass(file)"></i>
        {{ file.path_lower.replace(stripString,'') }}
      </a>
    </div>
    <div v-else v-on:click='expand(file); open = !open'>
      <i :class="fileClass(file, open)"></i>
      {{ file.path_lower.replace(thisStrip,'') }}/
      <i class="fa fa-cog fa-spin" v-if="waiting && open"></i>
      <small v-if="empty">
        (empty)
      </small>
    </div>
    <div v-if="files && open">
      <file-explorer :expand-files='files' :strip-string='childrenStrip'>
    </div>
  </div>
</script>

<script type="text/x-template" id="file-explorer-template">
  <div class='file-explorer tree'>
    <div v-for="file in files" class='line'>
      <folder :file='file' :strip-string='stripString'></folder>
    </div>

  </div>
</script>

  <script>
  function fileClass(file, open){
    var str = "fa fa-" + file[".tag"]
    if(open)
      str += '-open'
    return str
  }
  function filesFromApi(path, callback){
    <% if @site.db_path.present? %>
      url = '/api/dropbox/files?access_token=<%= @identity.full_access_token %>&path=' + path
    <% else %>
      url = '/api/<%= @site.provider %>/files?access_token=<%= @identity.access_token %>&path=' + path + '&site_id=<%= @site.id %>'
    <% end %>
    // <%= @identity.inspect.html_safe %>
    console.log(url)
    $.ajax({
      url: url,
      success: callback
    });
  }
  Vue.component('folder',{
    template: '#folder-template',
    props: ['file', 'strip-string'],
    data: function(){
      return {
        files: null,
        open: false,
        thisStrip: (this.stripString || '/<%= @site.name %>/'),
        childrenStrip: '',
        waiting: false,
        empty: false
      }
    },
    methods: {
      fileClass: fileClass,
      expand: function(file){
        var self = this
        self.childrenStrip = file.path_lower + '/'
        self.waiting = true
        if(this.files){
          self.waiting = false
          return
        }
        return filesFromApi(file.path_lower, function(files){
          self.files = files
          if(files.length == 0){
            self.empty = true
          }
          self.waiting = false
        })
      },
      canShowLink: function(file){
        return file[".tag"] == 'file'
      },
      link: function (file, url, dbPath, siteName){
        var replace = dbPath || "/" + siteName + "/"
        return "<%= @site.protocol %>" + url + "/" + file.path_lower.replace(replace,"")
      },
    }
  })
  Vue.component('file-explorer',{
    template: '#file-explorer-template',
    props: ['expand-files','strip-string'],
    data: function(){
      var self = this;
      return {
        files: this.expandFiles || this.filesFromApi(this.stripString, function(files){
          console.log(files)
          self.files = files
        }),
        open: false,
        strip: this.stripString
      }
    },
    methods: {
      fileClass: fileClass,

      filesFromApi: filesFromApi
    }
  })

  var employees = new Vue({
    el: '#file-explorer',

  });


  </script>

  <% else %>

  <% end %>
</div>